version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongodb
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
        interval: 10s
        timeout: 5s
        retries: 3
  mongodb:
    image: mongo:6.0.2
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 27017:27017
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  mongodb:
